steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/r2d-interno-dev/presentaciongcpr2d:v1.2-$COMMIT_SHA', './presentaciongcpr2d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/r2d-interno-dev/presentaciongcpr2d:v1.2-$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'jobs', 'deploy', 'presentaciongcpr2d', '--image', 'gcr.io/r2d-interno-dev/presentaciongcpr2d:v1.2-$COMMIT_SHA', '--region', 'europe-west1']

images:
  - 'gcr.io/r2d-interno-dev/presentaciongcpr2d:v1.2-$COMMIT_SHA'

logsBucket: 'gs://presentaciongcpr2d/log_exports'